/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

//! RDMA backend implementations.

#[cfg(any(test, feature = "test-utils"))]
pub mod cuda_test_utils;
pub mod ibverbs;
pub mod tcp;

use std::fmt::Debug;
use std::time::Duration;

use anyhow::Result;
use async_trait::async_trait;
use hyperactor::context;
use serde::Deserialize;
use serde::Serialize;
use serde::de::DeserializeOwned;
use typeuri::Named;

use crate::RdmaOp;
use crate::RdmaTransportLevel;
use crate::backend::ibverbs::efa_device::EfaDevice;
use crate::backend::ibverbs::ionic_device::IonicDevice;
use crate::backend::ibverbs::manager_actor::IbvBackend;
use crate::backend::ibverbs::mlx_device::MlxDevice;
use crate::backend::ibverbs::primitives::IbvConfig;
use crate::backend::tcp::manager_actor::TcpBackend;
use crate::device_selection::MemoryLocation;
use crate::device_selection::PciPath;
use crate::local_memory::KeepaliveLocalMemory;
use crate::rdma_components::RdmaRemoteBuffer;

/// Configuration for spawning RDMA backends.
#[derive(Debug, Clone, Default)]
pub struct RdmaConfig {
    /// Configuration for ibverbs-based backends.
    pub(crate) ibv: Option<IbvConfig>,
}

/// A transport backend for RDMA operations.
///
/// Implementors (e.g. [`IbvBackend<I>`], [`TcpBackend`]) are assembled
/// into the [`RdmaBackendHandle`] and [`RdmaRemoteBackends`] registries
/// by [`register_rdma_backends!`].
#[async_trait]
pub trait RdmaBackend: Clone + Debug + Send + Sync + 'static {
    /// Serializable per-buffer context carried on the wire.
    type RemoteBackendContext: Clone + Debug + Serialize + DeserializeOwned + Send + Sync + 'static;

    /// Backend-specific transport details (e.g. a cffi struct with raw
    /// ibverbs handles for GPU-initiated RDMA).
    type TransportInfo;

    /// Whether this backend is available on this host in the current proc.
    /// Returns false if the backend is supported on the host but is
    /// disabled by a config.
    fn available() -> bool;

    /// The transport level this backend provides.
    fn transport_level(&self) -> RdmaTransportLevel;

    /// Low-level transport details for direct control over RDMA
    /// operations (e.g. from a GPU kernel).
    fn transport_info(&self) -> Option<Self::TransportInfo>;

    /// The PCIe path from memory at `location` to the NIC this backend would
    /// serve it from. [`RdmaBackends::register_all`] compares these to pick
    /// between backends when a host has more than one. `None`, the default,
    /// means the backend is not ranked by locality and always serves.
    fn path_to(&self, _location: MemoryLocation) -> Option<PciPath> {
        None
    }

    /// Spawn the backend's actor(s) as children of `cx` and return its handle.
    async fn spawn(cx: &(impl context::Actor + Send + Sync), config: &RdmaConfig) -> Result<Self>
    where
        Self: Sized;

    /// Register `local` for remote access and return its wire context.
    async fn register_remote_buffer(
        &self,
        cx: &(impl context::Actor + Send + Sync),
        remote_buf_id: usize,
        local: KeepaliveLocalMemory,
    ) -> Result<Self::RemoteBackendContext>;

    /// Release a buffer registration by id.
    async fn release_buffer(
        &self,
        cx: &(impl context::Actor + Send + Sync),
        remote_buf_id: usize,
    ) -> Result<()>;

    /// Submit a batch of ops to this backend.
    async fn submit(
        &self,
        cx: &(impl context::Actor + Send + Sync),
        ops: Vec<RdmaOp>,
        timeout: Duration,
    ) -> Result<()>;
}

/// Resolves backend `B`'s context from a buffer's advertised backends.
/// One impl per backend is generated by [`register_rdma_backends!`].
pub(crate) trait ResolveRemoteBackendContext<B: RdmaBackend> {
    fn resolve(&self) -> Option<B::RemoteBackendContext>;
}

/// Which backends should serve a buffer, given each one's
/// [`RdmaBackend::path_to`] the buffer (in registration order).
///
/// An unranked backend (`None`) always serves. A ranked backend serves unless
/// another ranked backend has a strictly better path, so a host with several
/// NIC backends serves each buffer from the NICs closest to it rather than
/// from whichever backend is listed first, and tied backends all serve. With
/// at most one ranked backend, every backend serves.
fn serving_backends(paths: &[Option<PciPath>]) -> Vec<bool> {
    let best = paths
        .iter()
        .flatten()
        .copied()
        .reduce(|a, b| if b.is_better_than(&a) { b } else { a });
    paths
        .iter()
        .map(|path| match (path, &best) {
            (Some(path), Some(best)) => !best.is_better_than(path),
            _ => true,
        })
        .collect()
}

/// Derives the per-process RDMA backend registry from a list of
/// `Variant: Handle` pairs, where each `Handle` implements
/// [`RdmaBackend`].
///
/// The expansion defines [`RdmaRemoteBackends`] (a buffer's per-backend
/// wire contexts) with its [`ResolveRemoteBackendContext`] impls and
/// `RdmaRemoteBuffer::resolve_<name>` accessors, [`RdmaBackendHandle`]
/// and its `submit` dispatch, and [`RdmaBackends`] (the proc's spawned
/// backends). The list order is the routing priority among the backends a
/// buffer advertises; which NIC backends advertise it is decided by locality
/// (see [`serving_backends`]).
macro_rules! register_rdma_backends {
    ($($variant:ident: $handle:ty),+ $(,)?) => {
        paste::paste! {
            /// The backends a buffer is reachable through, one slot per backend.
            #[derive(Debug, Clone, Serialize, Deserialize, Named, Default)]
            pub(crate) struct RdmaRemoteBackends {
                $(pub(crate) [<$variant:lower>]: Option<<$handle as RdmaBackend>::RemoteBackendContext>,)+
            }

            $(
                impl ResolveRemoteBackendContext<$handle> for RdmaRemoteBuffer {
                    fn resolve(&self) -> Option<<$handle as RdmaBackend>::RemoteBackendContext> {
                        self.[<resolve_ $variant:lower>]()
                    }
                }
            )+

            impl RdmaRemoteBuffer {
                $(
                    /// Context for this backend, if the buffer advertises it.
                    pub fn [<resolve_ $variant:lower>](
                        &self,
                    ) -> Option<<$handle as RdmaBackend>::RemoteBackendContext> {
                        self.backends.[<$variant:lower>].clone()
                    }
                )+

                /// Whether this buffer advertises a backend compatible with `handle`.
                pub(crate) fn is_compatible_with(&self, handle: &RdmaBackendHandle) -> bool {
                    match handle {
                        $(
                            RdmaBackendHandle::$variant(_) => {
                                self.backends.[<$variant:lower>].is_some()
                            }
                        )+
                    }
                }
            }

            /// The backends spawned on this proc.
            #[derive(Debug, Default)]
            pub(crate) struct RdmaBackends {
                $([<$variant:lower>]: Option<$handle>,)+
            }

            impl RdmaBackends {
                /// Spawn every [`available`](RdmaBackend::available) backend.
                /// A backend that fails to spawn is skipped; bails only if no
                /// backend spawns.
                pub(crate) async fn spawn_available(
                    cx: &(impl context::Actor + Send + Sync),
                    config: &RdmaConfig,
                ) -> Result<Self> {
                    let mut backends = Self::default();
                    let mut errors: Vec<String> = Vec::new();
                    $(
                        if <$handle as RdmaBackend>::available() {
                            match <$handle as RdmaBackend>::spawn(cx, config).await {
                                Ok(handle) => backends.[<$variant:lower>] = Some(handle),
                                Err(e) => errors.push(format!("{}: {e}", stringify!($variant))),
                            }
                        }
                    )+
                    if backends.is_empty() {
                        if errors.is_empty() {
                            anyhow::bail!("no RDMA backend available");
                        }
                        anyhow::bail!(
                            "all available RDMA backends failed to initialize: {}",
                            errors.join("; ")
                        );
                    }
                    if !errors.is_empty() {
                        tracing::warn!("some RDMA backends failed to initialize: {}", errors.join("; "));
                    }
                    Ok(backends)
                }

                fn is_empty(&self) -> bool {
                    $(self.[<$variant:lower>].is_none() &&)+ true
                }

                /// Handles for all spawned backends, in priority order.
                pub(crate) fn handles(&self) -> Vec<RdmaBackendHandle> {
                    let mut handles = Vec::new();
                    $(
                        if let Some(handle) = &self.[<$variant:lower>] {
                            handles.push(RdmaBackendHandle::$variant(handle.clone()));
                        }
                    )+
                    handles
                }

                /// Register `local` with every spawned backend that should
                /// serve it: those [`serving_backends`] keeps, so on a host
                /// with several NIC backends only the ones with the best path
                /// to `local` advertise it. On the first failure, release the
                /// backends that already registered and return that error.
                pub(crate) async fn register_all(
                    &self,
                    cx: &(impl context::Actor + Send + Sync),
                    remote_buf_id: usize,
                    local: KeepaliveLocalMemory,
                ) -> Result<RdmaRemoteBackends> {
                    let location = local.location();
                    let paths = [$(
                        self.[<$variant:lower>]
                            .as_ref()
                            .and_then(|handle| <$handle as RdmaBackend>::path_to(handle, location)),
                    )+];
                    let mut serving = serving_backends(&paths).into_iter();
                    let mut remotes = RdmaRemoteBackends::default();
                    $(
                        let serves = serving.next().expect("one entry per backend");
                        if self.[<$variant:lower>].is_some() && !serves {
                            tracing::debug!(
                                "not registering {location:?} memory on {}: another backend has a closer NIC",
                                stringify!($variant),
                            );
                        }
                        if let Some(handle) = &self.[<$variant:lower>]
                            && serves
                        {
                            match <$handle as RdmaBackend>::register_remote_buffer(
                                handle,
                                cx,
                                remote_buf_id,
                                local.clone(),
                            )
                            .await
                            {
                                Ok(context) => remotes.[<$variant:lower>] = Some(context),
                                Err(e) => {
                                    // Release only the backends that already
                                    // registered: this one failed and later
                                    // ones were never reached.
                                    if let Err(release_err) =
                                        self.release_registered(cx, remote_buf_id, &remotes).await
                                    {
                                        tracing::warn!("failed to release remote buffers after registration failure: {release_err}");
                                    }
                                    return Err(e);
                                }
                            }
                        }
                    )+
                    Ok(remotes)
                }

                /// Release `remote_buf_id` from only the backends that
                /// successfully registered (those present in `registered`),
                /// accumulating any failures.
                async fn release_registered(
                    &self,
                    cx: &(impl context::Actor + Send + Sync),
                    remote_buf_id: usize,
                    registered: &RdmaRemoteBackends,
                ) -> Result<()> {
                    let mut errors: Vec<String> = Vec::new();
                    $(
                        if let Some(handle) = &self.[<$variant:lower>]
                            && registered.[<$variant:lower>].is_some()
                        {
                            if let Err(e) =
                                <$handle as RdmaBackend>::release_buffer(handle, cx, remote_buf_id).await
                            {
                                errors.push(format!("({}) {e}", stringify!($variant)));
                            }
                        }
                    )+
                    if errors.is_empty() {
                        Ok(())
                    } else {
                        anyhow::bail!(
                            "RDMA release failed on {} backend(s):\n{}",
                            errors.len(),
                            errors.join("\n")
                        )
                    }
                }

                /// Release `remote_buf_id` from every spawned backend,
                /// accumulating any failures.
                pub(crate) async fn release_all(
                    &self,
                    cx: &(impl context::Actor + Send + Sync),
                    remote_buf_id: usize,
                ) -> Result<()> {
                    let mut errors: Vec<String> = Vec::new();
                    $(
                        if let Some(handle) = &self.[<$variant:lower>] {
                            if let Err(e) =
                                <$handle as RdmaBackend>::release_buffer(handle, cx, remote_buf_id).await
                            {
                                errors.push(format!("({}) {e}", stringify!($variant)));
                            }
                        }
                    )+
                    if errors.is_empty() {
                        Ok(())
                    } else {
                        anyhow::bail!(
                            "RDMA release failed on {} backend(s):\n{}",
                            errors.len(),
                            errors.join("\n")
                        )
                    }
                }
            }
        }

        wirevalue::register_type!(RdmaRemoteBackends);

        /// Handle to a spawned backend.
        #[derive(Debug, Clone)]
        pub enum RdmaBackendHandle {
            $($variant($handle),)+
        }

        impl RdmaBackendHandle {
            /// The backend's name, for diagnostics.
            pub(crate) fn backend_name(&self) -> &'static str {
                match self {
                    $(RdmaBackendHandle::$variant(_) => stringify!($variant),)+
                }
            }

            /// Submit `ops` to this backend.
            pub(crate) async fn submit(
                &self,
                cx: &(impl context::Actor + Send + Sync),
                ops: Vec<RdmaOp>,
                timeout: Duration,
            ) -> Result<()> {
                match self {
                    $(
                        RdmaBackendHandle::$variant(handle) => {
                            <$handle as RdmaBackend>::submit(handle, cx, ops, timeout).await
                        }
                    )+
                }
            }
        }
    };
}

register_rdma_backends! {
    Mlx: IbvBackend<MlxDevice>,
    Efa: IbvBackend<EfaDevice>,
    Ionic: IbvBackend<IonicDevice>,
    Tcp: TcpBackend,
}

#[cfg(test)]
mod tests {
    use hyperactor::ActorEnvironment;
    use hyperactor::Proc;
    use hyperactor::RemoteSpawn;
    use hyperactor::channel::ChannelAddr;
    use hyperactor::channel::ChannelTransport;

    use super::*;
    use crate::RdmaManagerActor;
    use crate::RdmaManagerMessageClient;
    use crate::backend::ibverbs::device::IbvDevice;
    use crate::backend::ibverbs::device_selection::IbvDeviceTarget;
    use crate::backend::ibverbs::device_selection::best_ibv_path;
    use crate::backend::ibverbs::device_selection::get_pci_address;
    use crate::backend::ibverbs::device_selection::select_optimal_ibv_devices;
    use crate::backend::ibverbs::primitives::IbvDeviceInfo;
    use crate::device_selection::PathType;

    fn path(path_type: PathType, bottleneck_mbytes_per_sec: u32) -> Option<PciPath> {
        Some(PciPath {
            path_type,
            bottleneck_mbytes_per_sec,
        })
    }

    #[test]
    fn a_lone_nic_backend_always_serves() {
        // Mlx-only or EFA-only hosts: one ranked backend plus TCP. Whatever its
        // path, it serves, so these hosts register exactly as before.
        for only in [
            path(PathType::Pix, 50_000),
            path(PathType::Sys, 1),
            path(PathType::Dis, 0),
        ] {
            assert_eq!(serving_backends(&[only, None, None, None]), [true; 4]);
            assert_eq!(serving_backends(&[None, only, None, None]), [true; 4]);
        }
        assert_eq!(serving_backends(&[None, None, None, None]), [true; 4]);
    }

    #[test]
    fn a_more_local_nic_backend_wins() {
        // [Mlx, Efa, Ionic, Tcp] for GPU memory on NUMA node 1 of a host whose
        // only mlx5 NIC is on node 0: the ionic NIC shares the GPU's node.
        assert_eq!(
            serving_backends(&[
                path(PathType::Sys, 25_000),
                None,
                path(PathType::Phb, 50_000),
                None,
            ]),
            [false, true, true, true],
        );
        // Locality beats bandwidth.
        assert_eq!(
            serving_backends(&[
                path(PathType::Pix, 1),
                None,
                path(PathType::Phb, 50_000),
                None
            ]),
            [true, true, false, true],
        );
    }

    #[test]
    fn equally_local_nic_backends_rank_by_bandwidth_and_tie() {
        // Same NUMA node: the 400 Gb/s ionic NIC beats the 200 Gb/s mlx5 one.
        assert_eq!(
            serving_backends(&[
                path(PathType::Phb, 25_000),
                None,
                path(PathType::Phb, 50_000),
                None,
            ]),
            [false, true, true, true],
        );
        // A full tie keeps both, so list order breaks it as it did before.
        assert_eq!(
            serving_backends(&[
                path(PathType::Phb, 50_000),
                None,
                path(PathType::Phb, 50_000),
                None,
            ]),
            [true; 4],
        );
    }

    #[test]
    fn a_nic_backend_with_no_nic_for_the_buffer_yields() {
        // `nic:ionic_3` pins the manager to one ionic NIC; Mlx has no such NIC.
        assert_eq!(
            serving_backends(&[path(PathType::Dis, 0), None, path(PathType::Sys, 1), None]),
            [false, true, true, true],
        );
    }

    /// On a host with ionic NICs, the backends an [`RdmaManagerActor`] spawns
    /// (through [`RdmaBackends::spawn_available`]) include Ionic. Skips when no
    /// ionic device is present.
    #[timed_test::async_timed_test(timeout_secs = 60)]
    async fn spawn_available_includes_ionic_when_present() {
        if IbvDevice::<IonicDevice>::list().is_empty() {
            eprintln!("no ionic devices on this host; skipping");
            return;
        }
        let mut proc = Proc::direct(
            ChannelAddr::any(ChannelTransport::Unix),
            "spawn_available_ionic".to_string(),
        )
        .expect("create proc");
        let client = proc.client("test_client");
        let rdma_actor = RdmaManagerActor::new(None, &ActorEnvironment::default())
            .await
            .expect("create RdmaManagerActor");
        let rdma_handle = proc.spawn(rdma_actor);
        let names: Vec<&str> = rdma_handle
            .get_backend_handles(&client)
            .await
            .expect("get backend handles")
            .iter()
            .map(|handle| handle.backend_name())
            .collect();
        println!("spawned RDMA backends, in priority order: {names:?}");
        assert!(names.contains(&"Ionic"), "Ionic not spawned: {names:?}");

        proc.destroy_and_wait(Duration::from_secs(10), "test done")
            .await
            .expect("destroy proc");
    }

    /// The NIC backends' paths to `location` in registration order
    /// `[Mlx, Efa, Ionic, Tcp]`, as [`RdmaBackends::register_all`] sees them
    /// for a manager with device target `target`.
    fn nic_paths(
        location: MemoryLocation,
        target: Option<&IbvDeviceTarget>,
    ) -> [Option<PciPath>; 4] {
        [
            best_ibv_path::<MlxDevice>(location, target).ok(),
            best_ibv_path::<EfaDevice>(location, target).ok(),
            best_ibv_path::<IonicDevice>(location, target).ok(),
            None,
        ]
    }

    /// On a host with ionic NICs, using real sysfs topology (host memory, so
    /// no GPU driver is needed): host memory on a NUMA node is served by the
    /// ionic NICs on that node, and a manager pinned to one NIC is served by
    /// that NIC's backend alone. Prints what each backend offers. Skips without
    /// ionic NICs.
    #[test]
    fn nic_backend_choice_on_this_host() {
        let ionic = IbvDevice::<IonicDevice>::list();
        if ionic.is_empty() {
            eprintln!("no ionic devices on this host; skipping");
            return;
        }
        let numa_of = |nic: &IbvDeviceInfo| {
            let addr = get_pci_address(nic).expect("NIC has a PCI address");
            std::fs::read_to_string(addr.sysfs_path().join("numa_node"))
                .expect("read numa_node")
                .trim()
                .to_string()
        };
        let mut numas: Vec<String> = ionic.iter().map(numa_of).collect();
        numas.sort();
        numas.dedup();

        let mut locations = vec![MemoryLocation::Cpu(None)];
        locations.extend(
            numas
                .iter()
                .filter_map(|numa| numa.parse().ok())
                .map(|numa| MemoryLocation::Cpu(Some(numa))),
        );
        for location in locations {
            let paths = nic_paths(location, None);
            let serving = serving_backends(&paths);
            let chosen =
                select_optimal_ibv_devices::<IonicDevice>(location).expect("rank ionic NICs");
            println!(
                "{location:?}: mlx {:?} ionic {:?} serving [Mlx, Efa, Ionic, Tcp] = {serving:?} ionic NICs {:?}",
                paths[0],
                paths[2],
                chosen.iter().map(|nic| nic.name()).collect::<Vec<_>>(),
            );
            if let MemoryLocation::Cpu(Some(numa)) = location {
                for nic in &chosen {
                    assert_eq!(numa_of(nic), numa.to_string(), "{} is off node", nic.name());
                }
            }
        }

        // A manager pinned to an ionic NIC is served by Ionic alone, and one
        // pinned to another backend's NIC is not served by Ionic.
        let pinned = IbvDeviceTarget::nic(ionic[0].name().clone());
        let serving = serving_backends(&nic_paths(MemoryLocation::Cpu(None), Some(&pinned)));
        println!("pinned to {pinned:?}: serving {serving:?}");
        assert_eq!(serving, [false, false, true, true]);
        if let Some(mlx) = IbvDevice::<MlxDevice>::list().first() {
            let pinned = IbvDeviceTarget::nic(mlx.name().clone());
            let serving = serving_backends(&nic_paths(MemoryLocation::Cpu(None), Some(&pinned)));
            println!("pinned to {pinned:?}: serving {serving:?}");
            assert_eq!(serving, [true, false, false, true]);
        }
    }
}
